# Generated by Django 4.0 on 2021-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itemwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('unitprice', models.CharField(max_length=300)),
                ('qty', models.CharField(max_length=300)),
                ('returns', models.CharField(max_length=300)),
                ('netsales', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=300)),
                ('grossprofit', models.CharField(max_length=300)),
                ('profitpercent', models.CharField(max_length=300)),
            ],
        ),
    ]
