# Generated by Django 4.0 on 2021-12-31 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwise',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 12, 31, 10, 27, 52, 703594, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemwise',
            name='date',
            field=models.CharField(max_length=300),
        ),
    ]
