# Generated by Django 4.0 on 2001-01-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admind', '0002_itemwise_name_alter_itemwise_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorywise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('grosssales', models.CharField(max_length=300)),
                ('returns', models.CharField(max_length=300)),
                ('netsales', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('grossprofit', models.CharField(max_length=300)),
                ('profitpercent', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Endoftheday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('ticketid', models.CharField(max_length=300)),
                ('discount', models.CharField(max_length=300)),
                ('grosssales', models.CharField(max_length=300)),
                ('totalrecieved', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hourlysales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('period', models.CharField(max_length=300)),
                ('checks', models.CharField(max_length=300)),
                ('sales', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='paymentrecieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('trans', models.CharField(max_length=300)),
                ('paymenttype', models.CharField(max_length=300)),
                ('ticketid', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Salesreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('grosssales', models.CharField(max_length=300)),
                ('returns', models.CharField(max_length=300)),
                ('netsales', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=300)),
                ('grossprofit', models.CharField(max_length=300)),
                ('profitpercent', models.CharField(max_length=300)),
            ],
        ),
    ]
